### DISCUSSION TITLE
Audit performance

### DISCUSSION THREAD

**Discussion by shin-nien** [open-policy-agent/community#112] [Gatekeeper]
Posting a bit of fyi of our experience and I'm trying to find out a bit more about how Audit works for capacity planning reasons.

Our current Kubernetes setup:
- We run about 10k pods across 2000 deployments
- Everything's in dry-run
- We generate about 72k of violations on each run
- We switched to the discovery-client because "audit-from-cache" used >24Gi of memory
- Our controller settings:

```
  - --operation=audit
  - --operation=status
  - --logtostderr
  - --audit-chunk-size=0
  - --audit-from-cache=false
  - --audit-interval=300
  - --audit-match-kind-only=true
```

- Config

```
  sync:
    syncOnly:
    - group: ""
      kind: Namespace
      version: v1
    - group: extensions
      version: v1beta1
      kind: Ingress
```

With these settings we get reasonable audit times of ~60 minutes. CPU is ~1.75 cores and <1Gi of memory.

But with a bigger config we started to see issues:
```
    syncOnly:
    - group: ""
      kind: Namespace
      version: v1
    - group: extensions
      version: v1beta1
      kind: Ingress
    - group: policy
      version: v1beta1
      kind: PodDisruptionBudget
    - group: apps
      version: v1
      kind: Deployment
    - group: apps
      version: v1
      kind: ReplicaSet
    - group: apps
      version: v1
      kind: StatefulSet
    - group: apps
      version: v1
      kind: DaemonSet
    - group: batch
      version: v1
      kind: Job
    - group: batch
      version: v1beta1
      kind: CronJob
```

We observed that if we added more resources to `syncOnly` then Audit's healthchecks would start to fail intermittently and seemed to be affecting audit overall e.g. you stop seeing violations appear in the logs until much later. We don't have constraints/policies that rely on `data.inventory` yet so we didn't think there's any reason why adding more to the internal cache would cause Audit issues. Can anyone explain why a difference in sync config would make a difference?
