### DISCUSSION TITLE
Load bundle from backup service

### DISCUSSION THREAD

**Discussion by rmetcalf9** [open-policy-agent/community#139] [OPA and Rego]
We are deploying opa across multiple microservices. Each will have a number of agents and these agents are configured to download the bundle file from a s3 bucket.

I have been told to implement redundancy in this process. If one s3 bucket in one region goes down I need the opa agent to get the bundle from a second region.

I would like to be able to make a configuration something like this:

```
services:
  s3:
    url: https://my-bundle-bucket-a.s3.eu-west-1.amazonaws.com
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: eu-west-1
  s3b:
    url: https://my-bundle-bucket-b.s3.eu-west-1.amazonaws.com
    credentials:
      s3_signing:
        metadata_credentials:
          aws_region: eu-west-1

bundles:
  authz:
    service: s3, s3b
    resource: live-policy-bundle.tar.gz
    persist: true
    polling:
      min_delay_seconds: 30
      max_delay_seconds: 60
```

Then the bundle will use service s3 to poll for the bundle and if that fails it will go to service s3b and use a different bucket.
I have checked and the etags on both buckets match so there won't be an issue there.

I don't think a config like the above can work. I have also tried having multiple authz bundles but this didn't work either.
What do you recommend as the best strategy for having agents access redundant bundle locations?

Robert
