### DISCUSSION TITLE
How to limit constraint to a subset of namespaces?

### DISCUSSION THREAD

**Discussion by thomasmckay** [open-policy-agent/community#19] [Gatekeeper] [answered]
The ConstraintTemplate and Constraint below are preventing Pods from starting in _any_ namespace. Is there a way to do this? I was following (roughly) the examples [here](https://cloud.google.com/kubernetes-engine/docs/how-to/pod-security-policies-with-gatekeeper#enabling_constraints_and_constraint_templates).

```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            labels:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
	package k8srequiredlabels

	violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_]}
          ns := input.review.object.metadata.namespace
          missing := required - provided
          count(missing) > 0
          msg := sprintf("you must provide labels in namespace \"%s\": %v", [ns, missing])
	}
```
```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-gk
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["gatekeeper"]
  namespaces:
    - "testing-gatekeeper"
```
