### DISCUSSION TITLE
How to setup OPA for Azure AD?

### DISCUSSION THREAD

**Discussion by mukundv18** [open-policy-agent/community#201] [Envoy]
I am new to OPA as well as Azure AD. I have written the following sample config for OPA,

```
services:
  wmtopa:
    credentials:
      oauth2:
        token_url: https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token
        client_id: "<CLIENT_ID>"
        client_secret: "<CLIENT_SECRET>"
```

Registered a new application on Azure AD and configured it with Client Secret.

When the authentication is triggered, I get the following logs from OPA,

```
{"client_addr":"127.0.0.1:54232","level":"info","msg":"Received request.","req_id":2,"req_method":"PRI","req_path":"*","time":"2022-05-17T04:55:27Z"}
{"client_addr":"127.0.0.1:54232","level":"info","msg":"Sent response.","req_id":2,"req_method":"PRI","req_path":"*","resp_bytes":0,"resp_duration":0.119711,"resp_status":301,"time":"2022-05-17T04:55:27Z"}
```

What am I missing? Should something be configured in the Application Registration on Azure AD or should is there something missing in the config file for OPA?
