### DISCUSSION TITLE
OPA in github workflows

### DISCUSSION THREAD

**Discussion by javixeneize** [open-policy-agent/community#264] [OPA and Rego]
Hi

What is the best way to validate a JSON against an OPA policy in a github workflow? It would be the equivalent to run

opa run -s mypolicy.rego

Is there any existing github action to use in workflows to run opa? If not, this might be a good addition

Thanks

**Comment by srenatus** [comment]
You can use the [`setup-opa` action](https://github.com/open-policy-agent/setup-opa):

```yaml
name: Run OPA Tests  
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: Run OPA Tests 
      run: opa test tests/*.rego -v
```

Note that this won't work with `opa run -s`, since that's the _server mode_. But you can do `opa test`, or `opa parse`, whatever you want 😎
