### DISCUSSION TITLE
Using Artifactory as OCI registry host for OPA bundles

### DISCUSSION THREAD

**Discussion by harshiy24** [open-policy-agent/community#311] [OPA and Rego] [answered]
OPA can download bundles from OCI compatible registries. Artifactory is one such host that can have bundles stored as containers. We have the following config file:
```
services:
  docker-registry:
    url: https://docker-snapshot.net
    type: oci
    credentials:
      bearer:
        scheme: "Basic"
        token: "username:password"
bundles:
  authz:
    service: docker-registry
    resource: docker-snapshot.net/testorg/policy-deployment-policy/1.0.0
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
persistence_directory: /var/opa
```
When opa is run, this bundle is downloaded and works as expected. But these are the questions for our usecase:

- The point of having OPA fetch its bundles from Artifactory is to allow us to push changes without updating the OPA config each time. Is it possible to have OPA fetch the latest bundle by omitting the tag?
- If not, is it possible to say push a single tag called “latest” like Docker does and if so is OPA smart enough to automatically re-download it when it changes?

Can any of the above two points be satisfied using a specific config?
