### DISCUSSION TITLE
Error message when trying to load bundle through config file

### DISCUSSION THREAD

**Discussion by harshiy24** [open-policy-agent/community#313] [OPA and Rego] [answered]
We are using the following config.yaml file:
```
services:
  docker-registry:
    url: https://docker-snapshot.net
    type: oci
    credentials:
      bearer:
        scheme: "Basic"
        token: "username:password"
bundles:
  authz:
    service: docker-registry
    resource: docker-snapshot.net/testorg/policy-deployment-policy:1.0.0
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120
persistence_directory: /var/opa
```

When OPA is run using the following command:
`
opa run -s -c config.yaml
`
This is the output:
```
{"addrs":[":8181"],"diagnostic-addrs":[],"level":"info","msg":"Initializing server.","time":"2022-12-05T09:42:48-05:00"}
{"level":"error","msg":"Failed to load bundle from disk: bundle read failed: archive read failed: EOF","name":"authz","plugin":"bundle","time":"2022-12-05T09:42:48-05:00"}
{"level":"info","msg":"Starting bundle loader.","name":"authz","plugin":"bundle","time":"2022-12-05T09:42:48-05:00"}
{"current_version":"0.46.1","download_opa":"https://openpolicyagent.org/downloads/v0.47.0/opa_windows_amd64.exe","latest_version":"0.47.0","level":"info","msg":"OPA is out of date.","release_notes":"https://github.com/open-policy-agent/opa/releases/tag/v0.47.0","time":"2022-12-05T09:42:49-05:00"}
{"level":"info","msg":"Bundle loaded and activated successfully. Etag updated to e0d1aee2b52da4cb3cf0b8bc0c63dc7ed7ad7.","name":"authz","plugin":"bundle","time":"2022-12-05T09:42:49-05:00"}
```
What does the error: "Failed to load bundle from disk: bundle read failed: archive read failed: EOF" mean in this scenario?
The bundle is downloaded from Artifactory, but what does the error mean?
