### DISCUSSION TITLE
Decision log limit question

### DISCUSSION THREAD

**Discussion by sirpi** [open-policy-agent/community#332] [OPA and Rego] [answered]
Hi,
I have the following discovery agent config:

```
package config
discovery = {
    "bundles": { ... },
    "decision_logs": {
        "reporting": {
            "upload_size_limit_bytes": 1048576
        },
        "service": "<service-name>"
    },
    "status": {
        "service": "<service-name>"
    }
}
```

So I tried to limit the decision log size limit by 1MB. Though I realized that the decision log service (which has a size limit of 2MB just to be on the safe side) started throwing errors about the payload size being exceeded. So it seems that the agent (v0.48.0) does not respect this setting for some reason. Have I configured something wrong? Or what should be the expected behaviour when the size limit is exceeded on opa side? 
Thanks for your answers in advance.

**Comment by charlieegan3** [comment]
Hi Sirpi, thanks for your question. Would you be able to share the discovery configuration you're using with this. e.g.

```yaml
discovery:
  resource: bundles/discovery.tar.gz
  decision: discovery/config
  ... 
```

**Comment by sirpi** [comment]
Hi,

The base config has this structure:

```
services:
- name: storage-service
  ...
- name: decision-log-service
  url: <service-url>
  headers:
    agentId: <myId>
  credentials: ...
  tls: ...
discovery:
  name: agent-config
  resource: configurations/discovery.tar.gz
  service: storage-service
  decision: config/discovery
  signing:
    keyid: global_key
keys:
  global_key:
    key: ...
```

I hope you find something useful here and thanks for your help.
