### DISCUSSION TITLE
OAuth2 client credentials are passed in a non standard way

### DISCUSSION THREAD

**Discussion by royi-frontegg** [open-policy-agent/community#360] [OPA and Rego] [answered]
OAuth2 credentials are passed in a non-standard way to my token endpoint and I get the `client_id` & `client_secret` in `php-auth-user` & `php-auth-pw` headers.
To solve it I added `additional_parameters` with the same values in order to get them to pass in urlencoded form body.

configuration example 
```
services:
  my-service:
    url: https://my.bundle.location.com
    credentials:
      oauth2:
        token_url: "https://my-token-exchange-url.com"
        client_id: "aaaaa"
        client_secret: "ccccc"
```

Do you have any ideas what did I do wrong?
