### DISCUSSION TITLE
How to restrict pod forwarding to tiller using rego

### DISCUSSION THREAD

**Discussion by subravi92** [open-policy-agent/community#43] [Gatekeeper] [answered]
Hello, I am trying to restrict port forwarding to the tiller. I am not able to match subresource. for some reason, it is not working. tried in 2 ways.. any pointers would be helpful.
```
package kubernetes.admission
kind = {"Deployment","Pod","Service"}
deny[reason] {
    kind[input.request.kind.kind]
    input.request.subresource == "port-forward"
    name := input.request.object.metadata.name
    startswith(name,"tiller")
    reason := sprintf("You are not allowed to port-forward to tiller from %v namespace",[input.request.namespace]) 
}
package kubernetes.admission

deny[reason] {
    input.request.kind.kind == "PodPortForwardOptions"
    input.request.resource.resource == "pods"
    input.request.subResource == "portforward"
    name := input.request.object.metadata.name
    startswith(name,"tiller")
    reason := sprintf("You are not allowed to port-forward to tiller from %v namespace",[input.request.namespace])
}
```

**Comment by anderseknert** [comment, marked as answer]
Hi @subravi92 👋 

The second deny rule is almost there. However, it doesn't look like the metadata from the pod is carried into the `PodPortForwardOptions` admission review, so your rule fails at this line:

```rego
name := input.request.object.metadata.name
```

The name of the pod seems to be reflected in `input.request.name` though, so you could use that instead:

```rego
enforce[reason] {
    input.request.kind.kind == "PodPortForwardOptions"
    input.request.resource.resource == "pods"
    input.request.subResource == "portforward"
    name := input.request.name
    startswith(name, "tiller")
    reason := sprintf("You are not allowed to port-forward to tiller from %v namespace", [input.request.namespace])
}
```
I can recommend enabling the decision logging capabilities of OPA when you debug things like this, as it will allow you to see the full admission review object sent from the kubernetes API server.

**Reply by subravi92** [reply]
Thanks for your reply...Decision logs are already enabled but I don't see a port-forward admission review and tried the above rego snippet as well. didn't work.. am I missing something?
```
object."client_addr":ipaddr,"level":"info","msg":"Sent response.","req_id":67933,"req_method":"PUT","req_path":"/v1/policies/opa/port-forward-tiller-restriction-opa-policy/port-forward-tiller-restriction.rego","resp_bytes":2,"resp_duration":0.399905,"resp_status":200,"time":"2021-10-29T10:58:05Z"}
{"client_addr":"ipaddr","level":"info","msg":"Received request.","req_id":,"req_method":"PUT","req_path":"/v1/policies/opa/port-forward-tiller-restriction-opa-policy/port-forward-tiller-restriction.rego","time":"2021-10-29T10:59:08Z"}
```

**Reply by anderseknert** [reply]
The rule works well in my kind cluster:

```shell
$ kubectl port-forward nginx-test 8080 8080
error: error upgrading connection: admission webhook "validating-webhook.openpolicyagent.org" denied the request: Enforced: You are not allowed to port-forward to nginx-test from default namespace
```

What does your validating webhook configuration look like? If you don't see the `PodPortForwardOptions` resource sent by the API server it sounds like it's exempted from review.

**Reply by jsarkar** [reply]
Here is our validating webhook configuration `rules` look like:
 ```
objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pods
    - pods/exec
    - pods/portforward
    - deployments
    - services
    - ingresses
    - customresourcedefinitions
    - replicasets
    - daemonsets
    - jobs
    - cronjobs
    - namespaces
    - rolebindings
    - horizontalpodautoscalers
    - chaosblades
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 10
```
Do you mind to share your your validating webhook config?  Even we have the sub-resource defined, We can't see `PodPortForwardOptions` in debug log.

**Reply by jsarkar** [reply]
Do you mind to also post the version of opa?
mine is kube-mgmt :3.0.0 and opa:0.32.0
I have included all resources in the webhook. But still the same policy is not working for me
```
      service:
        name: opa
        namespace: opa
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: webhook.openpolicyagent.org
    namespaceSelector:
      matchExpressions:
      - key: openpolicyagent.org/webhook
        operator: NotIn
        values:
        - ignore
    objectSelector: {}
    rules:
    - apiGroups:
      - '*'
      apiVersions:
      - '*'
      operations:
      - '*'
      resources:
      - '*'
      scope: '*'
    sideEffects: None
    timeoutSeconds: 10
    ```

**Reply by anderseknert** [reply]
I know it's not intuitive, but `*` does **not** include all resources (i.e. no subresources). See the Kubernetes [docs](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-rules) on how to include those. If you just want to try everything you could use `*/*`, then you could try to scope it down to `pods/*` once you have something working.

**Reply by jsarkar** [reply]
sorry...that's my mistake while copy/pest. The validation webhook config look like this:
```
rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - '*/*'
```
 is it  could be opa/kube-mgmt version?  I have tested with latest opa/kube-mgmt and old. Both are not working for me.I don't even see the subresource shows up in opa log.
 
Here are 2 version  details, which I have tried:
 kube-mgmt:0.10
 opa:0.23.2-rootless
 and
 kube-mgmt :3.0.0
 opa:0.32.0
