### DISCUSSION TITLE
Gatekeeper Constraint not blocking the non - whitelisted image

### DISCUSSION THREAD

**Discussion by gviswalingam** [open-policy-agent/community#449] [Gatekeeper] [answered]
Hi We are using eks version 1.24 , Deployed gatekeeper via helm chart successfully into cluster.

Now added Constraint template with rego policy to allow only whitelisted images into pod as yaml file as part of helm chart. below is the code 

```
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8swhitelistedimages
spec:
  crd:
    spec:
      names:
        kind: k8sWhitelistedImages
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            images:
              type: array
              items: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8swhitelistedimages
        whitelisted_images = {images |
            images = input.parameters.images[_]
        }
    
        images_whitelisted(str, patterns) {
            image_matches(str, patterns[_])
        }
    
        image_matches(str, pattern) {
            contains(str, pattern)
        }
        violation[{"msg": msg}] {
          input.review.object
          image := input.review.object.spec.containers[_].image
          name := input.review.object.metadata.name
          not images_whitelisted(image, whitelisted_images)
          msg := sprintf("pod %q has invalid image %q. Please, contact your DevOps. Follow the whitelisted images %v", [name, image, whitelisted_images])
        }
```

After that added Constraint crd policy for whitelist images via below yaml file deployed through helm chart as well.

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sWhitelistedImages
metadata:
  name: k8senforcewhitelistedimages
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    images:
          - docker
```
          

Both Template and constraint were successful , verified by using the commands kubectl get constrainttemplate,constraint and also described and checked as well.

Now to test this I created a pod with image: busybox and its not whitelisted : below is the yaml file

```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
      runAsNonRoot: true

```

The pod is getting created , Actual behaviour should block this image and throw a error has invalid image Please, contact your DevOps. Follow the whitelisted image

Can someone please help me with it ?

Many thanks

**Comment by anderseknert** [comment]
The policy itself works as intended: https://play.openpolicyagent.org/p/1KGD25rK3N

Must be something missing in the configuration, or how it's set up. Not sure what that would be though.

**Reply by gviswalingam** [reply]
Hi @anderseknert  Any suggestion where and what to look ? Thanks

**Reply by anderseknert** [reply]
Not sure, but the schema for the parameters doesn't look right to me. Could you try something like this?

```yaml
openAPIV3Schema:
  type: object
  properties:
    images:
      type: array
      items:
        type: string
```
No idea whether that's the actual issue though. Anything in the logs?
