### DISCUSSION TITLE
[Need help] Add an annotation to all services of type LoadBalancer using OPA gatekeeper AssignMetadata mutation CRD

### DISCUSSION THREAD

**Discussion by spandan541** [open-policy-agent/community#457] [Gatekeeper]
Hi,

I need some help adding an annotation to all services of type LoadBalancer using the **AssignMetadata CRD**.

As of today, I am not sure if the [match section](https://open-policy-agent.github.io/gatekeeper/website/docs/mutation/#extent-of-changes) supports comparing fields in spec (eg: spec.type).
Hence I was wondering if there is any way to compare the value of `spec.type == LoadBalancer` in the AssignMetadata CRD

Proposed solution :-
Can we can filter out services by adding a `filter` field to the match section? Something like the example below :-
Eg: 
```
apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: demo-annotation-lb
spec:
  applyTo:
  - groups: [""]
    kinds: ["Service"]
    versions: ["v1"]
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Service"]
    filter:
    - path: "spec.type"
      value: LoadBalancer
  location: "metadata.annotations.svc_type"
  parameters:
    assign:
      value: "lb"
```

Please do suggest if this use case can already be solved using the existing CRDs. Looking forward to a few suggestions.
