### DISCUSSION TITLE
How to limit constraint to a specific label

### DISCUSSION THREAD

**Discussion by michaelm-88** [open-policy-agent/community#469] [Gatekeeper]
Ho can i update my constraint to include also the labels 

K8sPSPReadOnlyRootFilesystem in version "v1beta1" cannot be handled as a K8sPSPReadOnlyRootFilesystem: strict decoding error: unknown field "spec.match.labels"

```
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: psp-readonlyrootfilesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "kube-system"
    # labels:
    #  app.kubernetes.io/name: aws-ebs-csi-driver
    ```

**Comment by michaelm-88** [comment]
i find it 

```
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPReadOnlyRootFilesystem
metadata:
  name: psp-readonlyrootfilesystem
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: aws-ebs-csi-driver
        ```
