### DISCUSSION TITLE
Issue using harbor private registries with AWS storage behind harbor as my policy bundle server

### DISCUSSION THREAD

**Discussion by s004pmg** [open-policy-agent/community#541] [OPA and Rego]
For me, my setup works as a harbor public repo (if I remove the credential information), but not if I mark the harbor repo private. 

I've added all of the Amazon root CA's to my cert bundle reference from the opa-config:
```
    services:
      oci-registry:
        url: "https://my.oci.server.example/"
        type: oci
        tls:
          ca_cert: ${CA_CERT_FILE}

        credentials:
          bearer:
            scheme: "Basic"
            #scheme: "Bearer"
            token: "username:password"

```
From the OPA logs, some of the layers seem to come in alright?:
```
{
  "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
  "level": "debug",
  "msg": "do request",
  "request.header.accept": "application/vnd.oci.empty.v1+json, */*",
  "request.header.user-agent": "containerd/1.7.11+unknown",
  "request.method": "GET",
  "time": "2024-01-12T17:29:32Z",
  "url": "https://my.oci.server.example/path/to/bundle/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
}
```
But then not, with an HTTP 400:
```
{
  "digest": "sha256:e967dc5eb7d24250f5309b698221cdb8bc87a6f0f4cd7c0a5461de8a5ce5e1ea",
  "level": "debug",
  "msg": "fetch response received",
  "response.header.content-type": "application/xml",
  "response.header.date": "Fri, 12 Jan 2024 17:29:32 GMT",
  "response.header.server": "AmazonS3",
  "response.header.x-amz-id-2": "c41pck5x....",
  "response.header.x-amz-request-id": "FTA...",
  "response.status": "400 Bad Request",
  "time": "2024-01-12T17:29:32Z",
  "url": "https://my.oci.server.example/path/to/bundle/tag/blobs/sha256:e967dc5eb7d24250f5309b698221cdb8bc87a6f0f4cd7c0a5461de8a5ce5e1ea"
}
{
  "level": "error",
  "msg": "Bundle load failed: failed to pull my.oci.server.example/path/to/bundle:my_tag: download for 'my.oci.server.example/path/to/bundle:my_tag' failed: failed to ingest: copy failed: httpReadSeeker: failed open: unexpected status code https://my.oci.server.example/path/to/bundle/blobs/sha256:e967dc5eb7d24250f5309b698221cdb8bc87a6f0f4cd7c0a5461de8a5ce5e1ea: 400 Bad Request",
  "name": "authz",
  "plugin": "bundle",
  "time": "2024-01-12T17:29:32Z"
}
```
Nothing in the various Harbor logs seems helpful. My understanding is that the OCIDownloader is a little different than the normal service declaration. I'm hoping that I've just done the configuration wrong here?
