### DISCUSSION TITLE
How can I modify nodeAffinity in gatekeeper?

### DISCUSSION THREAD

**Discussion by dimm0** [open-policy-agent/community#572] [Gatekeeper]
I'm trying to write a ModifySet to modify a nodeAffinity. I have this deployed as a pod:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: NotIn
            values:
            - NVIDIA-TITAN-RTX
```

and I want it to become:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: NotIn
            values:
            - NVIDIA-TITAN-RTX
          - key: "topology.kubernetes.io/zone"
            operator: In
            values:
            - "my-topology-zone"
```

If there are multiple matchExpressions, I want to add to all.

What should I put in location?

```
  location: "spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions[]"
```

This doesn't work. Glob in square brackets doesn't work either. No brackets doesn't work.
