### DISCUSSION TITLE
How to call s3 from opa to fetch json data files

### DISCUSSION THREAD

**Discussion by akshay410** [open-policy-agent/community#585] [Community]
Is it possible to fetch json data files stored in s3  using http.send . i'm trying a simple http get request using below code
`httpResponse := http.send({
		"method" : "GET",
		"url" : url
	})`

with config.yaml having

```
  config:
    services:
      s3:
        url: https://{bucketName}.s3.ap-south-1.amazonaws.com
        dataFile: dataFile.json
        credentials:
          s3_signing:
            web_identity_credentials:
              aws_region: ap-south-1
```

I'm trying to access s3 using web identity credentials. i've created a role to access s3 which is attached to the EC2 where i'm running opa but it's giving access denied. can someone help me on how to send signed request instead of simple http call (how to fetch access key/secret key in opa to create a signed request)
