### DISCUSSION TITLE
is it possible to run opa with just the data being loaded from bundle

### DISCUSSION THREAD

**Discussion by akshay410** [open-policy-agent/community#588] [OPA and Rego]
i want to run opa server with policies being read from a certain folder and all the data file to be loaded using a bundle. is it possible to do in opa
below is my config.yaml 
```
services:
  s3:
    url: http://localhost:4566

bundles:
  authz:
    service: s3
    resource: my-bucket/bundle.tar.gz

paths:
  - /Users/userName/Downloads/policy/
  ```
  
paths is my path to folder where my policy files are present. in my bundle.tar.gz i have data.json containing all the data needed

i've tried running opa as 
opa run -s -c config.yaml
opa run -s policy/ -c config.yaml

but in both of these scenario i'm not getting any response. looks like opa is not able to load rego policies. can someone please help me on this
