### DISCUSSION TITLE
Can't catch undefined values in functions

### DISCUSSION THREAD

**Discussion by roco1234** [open-policy-agent/community#607] [OPA and Rego]
I want to write a policy to check that `GroupDescription` is defined and that IF `SecurityGroupEgress` AND/OR `SecurityGroupIngress` is defined, they both have `Description` defined

yaml
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: GroupName
      GroupDescription: GroupDescription
      SecurityGroupEgress: 
          - Description: GroupDescription
```

```
allow {
  security_group.GroupDescription
  all_rules_have_descriptions(security_group.SecurityGroupIngress)
  all_rules_have_descriptions(security_group.SecurityGroupEgress)
}

all_rules_have_descriptions(rules) {
    not rules
} {
    count([rule | rule := rules[_]; rule.Description]) == count(rules)
}
```

In this example the template check fails because `all_rules_have_descriptions(security_group.SecurityGroupIngress)` fails. Is there something I can do to get undefined to pass? I have also tried `== null`, `count(rules) == 0`

Or do I have to just explicitly check every scenario where ingress could be set but egress isn't etc
