### DISCUSSION TITLE
Persistance of docker volume of OPA Service not working

### DISCUSSION THREAD

**Discussion by Mel3530** [open-policy-agent/community#609] [OPA and Rego]
Hello, I have an OPA service configured in Docker Compose as follows:
```
opa:
  container_name: opa_dev
  image: openpolicyagent/opa
  command: ["run", "--server", "--addr", ":8282"]
  networks:
    - my-net
  volumes:
    - ./opa/data:/data
  ports:
    - 8282:8282
```
I have an empty directory named `./opa/data`. I'm able to start the container (opa_dev) without any errors in the logs. However, I'm facing an issue where new rules added via a curl request to an API are not persistently stored in the volume. I would greatly appreciate any help you can provide. I've searched many resources but haven't found a solution to fix it.
