### DISCUSSION TITLE
OPA input format for Http API requests

### DISCUSSION THREAD

**Discussion by gituserjava** [open-policy-agent/community#61] [Envoy] [answered]
In a use-case where OPA is being used as authorization provider from Envoy, what is the format with which OPA receives input from Envoy?

From postman I am calling my endpoint by passing the header `x-custom-header: foo`. It is first routed to envoy sidecar which in turn calls OPA and forwards the request headers to OPA. What is the format/pattern in which OPA receives the Http request? Please advise.

**Request example:**
```
GET /api/v1/employees/departments
Accept: */*
x-custom-header : foo
```

**Comment by srenatus** [comment, marked as answer]
> In a use-case where OPA is being used as authorization provider from Envoy, what is the format with which OPA receives input from Envoy?

The input format depends on the configured `transport_api_version` in Envoy 👇 

```yaml
          http_filters:
          - name: envoy.ext_authz
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              transport_api_version: V3
```

📚 See the [documentation of the _Input Document_](https://www.openpolicyagent.org/docs/latest/envoy-primer/#input-document)

For _multiple headers_, Envoy will include them in the `AttributeContext` separated by commas [(source)](https://github.com/envoyproxy/envoy/blob/45ec050f91407147ed53a999434b09ef77590177/api/envoy/service/auth/v3/attribute_context.proto#L114-L117):

```
    // The HTTP request headers. If multiple headers share the same key, they
    // must be merged according to the HTTP spec. All header keys must be
    // lower-cased, because HTTP header keys are case-insensitive.
```

(I've included that because of the extra info from the issue you've filed here: https://github.com/open-policy-agent/opa/issues/3985)
