### DISCUSSION TITLE
Issues with the default libraries of OPA Gatekeeper

### DISCUSSION THREAD

**Discussion by vruask** [open-policy-agent/community#62] [Gatekeeper]
Hey all, I'm trying to configure the constraint template taken from https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/template.yaml along with its constraint taken from https://github.com/open-policy-agent/gatekeeper-library/blob/master/library/pod-security-policy/host-namespaces/samples/psp-host-namespace/constraint.yaml

**Procedure followed:**
1. Used `kubectl apply -f template.yaml`  to configure the template. Got the response `constrainttemplate.templates.gatekeeper.sh/k8spsphostnamespace created`
2. Used `kubectl apply -f constraint.yaml`  to configure the constraint. Got the response `k8spsphostnamespace.constraints.gatekeeper.sh/psp-host-namespace created`
3. Tried installing the below Pod using `kubectl apply -f samplepod.yaml`

```
apiVersion: v1
kind: Pod
metadata:
  name: httpd-server
  labels:
    app: httpd-host-namespace
spec:
  hostPID: true
  hostIPC: true
  containers:
  - name: httpd
    image: httpd
```
**Expected behavior:** The pod is prevented from being created, because the hostPID and hostIPC = true. The pod 
should be created only if the value is false.
**Actual behavior:**  Pod gets created: `pod/httpd-server created`. The same behavior occurs, if hostPID and hostIPC = false. The logs are attached for both audit and controller-manager pods.
[audit.log](https://github.com/open-policy-agent/feedback/files/7495262/audit.log)
[controller-man.log](https://github.com/open-policy-agent/feedback/files/7495263/controller-man.log)

Not sure what I'm doing wrong here, since its basically the same template. Looking forward to your response!
