### DISCUSSION TITLE
Bundle fails to load

### DISCUSSION THREAD

**Discussion by AleksanderBrzozowski** [open-policy-agent/community#650] [Community]
Hi! We use OPA in production, in a few different k8s clusters.

Here is the config that we use:

```yaml
config:
  default_decision: /authz

  services:
    - name: policy-service
      url: http://policy-service.namespace:8080

  bundles:
    authz:
      service: policy-service
      resource: authz
      persist: true
      polling:
        min_delay_seconds: 10
        max_delay_seconds: 20

  persistence_directory: /var/opa

  decision_logs:
    console: true

  status:
    prometheus: true

  plugins:
    envoy_ext_authz_grpc:
      addr: :9191
      path: /authz
      dry-run: false
      enable-reflection: true
```

Basically, the bundle is fetched from policy-service, and persisted under /var/opa.

This is a mechanism that allows us to have a fallback in case there is a problem to fetch bundle from policy-service (network issue, or a service is down).

The `/var/opa` dir is a mounted volume, and is shared between multiple pods:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ...
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-dynamic-sc-a # AWS Elastic File System
```

The problem we are encountering is that OPA deployment in one of our k8s clusters fails to load bundle in most cases with such an error:

```
Bundle load failed: bundle read failed: failed to copy file x/data.json: unexpected EOF
```

From time to time bundle is loaded successfully, but in most cases it fails (based on the`bundle_failed_load_counter` and `bundle_loaded_counter`).

I wonder if you can help to find what might be the reason of this failure? The bundle is pretty big, it contains a lot of data. However, in four different kubernetes clusters, which use the same bundle, we don't have this issue.
