### DISCUSSION TITLE
http.send in docker with fastAPi and mongoDB

### DISCUSSION THREAD

**Discussion by davidArch** [open-policy-agent/community#675] [OPA and Rego]
Hello,
I am having trouble using http.send. 
This works:
```
curl -X GET "http://localhost:8000/models/by-name/newModel" 
{"message":"Modell erfolgreich abgerufen","data":{"_id":"67b6de1405094635dabc5922","name":"newModel","algorithm":"mlp"}}
```

This does not. Its loading for a while and then gives me a 200 OK. I tried localhost:8000 instead of  app:8000 but does not work either: 
```
package create_model
import future.keywords.in

response := http.send({
        "method": "get",
        "url": "http://app:8000/models/by-name/newModel"
    })

deny contains message if {
    input.name == "newModel"
    response.body.data.name == "newModel"
    message := "name already exists in DB"
}
```
using this request:
```
curl -X POST "http://localhost:8000/models/create-model" -H "Content-Type: application/json" -d '{
>     "name": "newModel",
>     "algorithm": "mlp"
> }'
{"message":"Modell erfolgreich erstellt","data":{"name":"newModel","algorithm":"mlp","_id":"67d0485c2b8ec26e92182ba4"}}
```
Simple deny rules evaluating input "name" or "algorithm" do work correctly. 
I would highly appreciate any feedback.

Thank you and kind regards
David

main.rego: 
```
package main
import data.create_model

default allow := false

allow if {
    count(create_model.deny) == 0
}
```
docker.compose
```
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - opa-network

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: "run --server --addr :8181"
    networks:
      - opa-network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - opa
    networks:
      - opa-network

networks:
  opa-network:

volumes:
  mongo_data:
```
