### DISCUSSION TITLE
Exclude /health endpoint from being traced in distributed tracing

### DISCUSSION THREAD

**Discussion by loekensgard** [open-policy-agent/community#686] [OPA and Rego] [answered]
Hi,

I am currently configuring distributed tracing for OPA using the following configuration:

```yaml
distributed_tracing:
  type: grpc
  address: <address>
  service_name: <custom_name>
  resource:
    deployment_environment: Dev/Qa/Prod
```
    
I would like to know if there is a way to exclude the /health endpoint from being traced. I am aware that other languages have filters to support this functionality, but I couldn't find any documentation for OPA regarding this. 

Any guidance or suggestions would be greatly appreciated.

Thank you!
