### DISCUSSION TITLE
OPA Retry question

### DISCUSSION THREAD

**Discussion by antonj7** [open-policy-agent/community#689] [OPA and Rego]
Hi everyone! 
I have a question, we're running opa as a lambda extension, our approach is based on [godaddy plugin](https://github.com/godaddy/opa-lambda-extension-plugin). 
The issue is that due to high traffic occasionally it fails to load opa bundle with a following error(once every 1-2k requests): 
- Bundle load failed: request failed: Get "https://bucket.s3.us-east-1.amazonaws.com/test-repo.tar.gz": context canceled
or 
- Bundle load failed: request failed: Get "https://bucket.s3.us-east-1.amazonaws.com/test-repo.tar.gz": net/http: timeout awaiting response headers

Is there a way to configure a retry for this? Thank you
Our current config: 
```
services:
  s3:
    url: https://bucket.s3.us-east-1.amazonaws.com
    credentials:
      s3_signing:
        environment_credentials: {}

bundles:
  kard:
    service: s3
    resource: test-rego.tar.gz
    polling:
      trigger: manual
      scope: write

decision_logs:
  console: true

plugins:
  lambda_extension:
    minimum_trigger_threshold: 30
    trigger_timeout: 7
```
