### DISCUSSION TITLE
Multiple bundles in config file

### DISCUSSION THREAD

**Discussion by ajeetmbr** [open-policy-agent/community#90] [OPA and Rego] [answered]
Can anyone share a sample for configuration file with multiple bundles

**Comment by anderseknert** [comment, marked as answer]
Sure, it would look something like this.

```yaml
services:
  - name: acmecorp
    url: https://example.com/service/v1
    credentials:
      bearer:
        token: "abc123"

bundles:
  bundle1:
    service: acmecorp
    resource: somedir/bundle1.tar.gz
  bundle2:
    service: acmecorp
    resource: somedir/bundle2.tar.gz
```

You'll need to be careful when using different bundles though, and have the [.manifest file](https://www.openpolicyagent.org/docs/latest/management-bundles/#bundle-file-format) in each bundle clearly define the roots owned by that bundle. In most cases it is better to simply use a single bundle.

**Reply by ajeetmbr** [reply]
Thanks

**Reply by Ronnie-personal** [reply]
> Sure, it would look something like this.
> 
> ```yaml
> services:
>   - name: acmecorp
>     url: https://example.com/service/v1
>     credentials:
>       bearer:
>         token: "abc123"
> 
> bundles:
>   bundle1:
>     service: acmecorp
>     resource: somedir/bundle1.tar.gz
>   bundle2:
>     service: acmecorp
>     resource: somedir/bundle2.tar.gz
> ```
> 
> You'll need to be careful when using different bundles though, and have the [.manifest file](https://www.openpolicyagent.org/docs/latest/management-bundles/#bundle-file-format) in each bundle clearly define the roots owned by that bundle. In most cases it is better to simply use a single bundle.

@anderseknert 
Could you please give an example of multiple bundles from multiple services URLs?

Thanks!

**Reply by charlieegan3** [reply]
It would look a bit like this:


```yaml
services:
  - name: service1
    url: https://example.com/service/1
    credentials:
      bearer:
        token: "abc123"
  - name: service2
    url: https://example.com/service/2
    credentials:
      bearer:
        token: "xyz123"

bundles:
  bundle1:
    service: service1
    resource: somedir/bundle1.tar.gz
  bundle2:
    service: service2
    resource: somedir/bundle2.tar.gz
```
